# Generated by Django 4.1.7 on 2023-02-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_vehicles_alter_profiles_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('total_spaces', models.IntegerField()),
                ('available_space', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.BooleanField()),
                ('updated_at', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Parking_Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField()),
                ('parking_space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.parking_lots')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(verbose_name=10)),
                ('cardholder_name', models.CharField(max_length=200)),
                ('expiration_date', models.DateField()),
                ('is_default', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.profiles')),
            ],
        ),
    ]
