# Generated by Django 4.1.7 on 2023-02-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0003_credit_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARKING_LOTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_name', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=200)),
                ('total_spaces', models.IntegerField()),
                ('available_spaces', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PARKING_RESERVATIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PARKING_SPACES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_space_name', models.CharField(max_length=200)),
                ('is_available', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
