# Generated by Django 4.1.7 on 2023-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_vehicles_alter_profiles_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CREDIT_CARDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('cardholder_name', models.CharField(max_length=200)),
                ('expiration_date', models.DateTimeField()),
                ('is_default', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
